#!/usr/bin/env python3
"""
Compute pass@k metrics from CVDP composite_report.json files.

Uses the Codex formula: pass@k = 1 - C(n-c, k) / C(n, k)
averaged over all problems, where n is the number of samples
and c is the number of correct samples per problem.

Usage:
    python3 scripts/compute_pass_at_k.py <work_dir> [work_dir2 ...]
    python3 scripts/compute_pass_at_k.py <work_dir> --json output.json

Data source: <work_dir>/composite_report.json (generated by run_samples.py)

Flow:
    run_benchmark.py -> sample_N/raw_result.json
    run_samples.py   -> combines into composite_report.json
    collect_metrics.py -> aggregates tokens/costs from metrics.json
    compute_pass_at_k.py -> computes pass@k from composite_report.json  (this script)
"""

import json
import argparse
import sys
from pathlib import Path
from collections import Counter
from typing import Dict, List, Tuple


def comb(n: int, k: int) -> int:
    if k > n or k < 0:
        return 0
    if k == 0:
        return 1
    if k > n - k:
        k = n - k
    r = 1
    for i in range(k):
        r = r * (n - i) // (i + 1)
    return r


def pass_at_k(n: int, c: int, k: int) -> float:
    return 1 - comb(n - c, k) / comb(n, k)


def compute_pass_at_k_from_composite(composite_path: str) -> Dict:
    with open(composite_path) as f:
        data = json.load(f)

    metadata = data["metadata"]
    n = metadata["n_samples"]
    model = metadata.get("model_agent", "unknown")
    dataset = metadata.get("dataset_path", "unknown")
    samples = data["samples"]

    problem_appearances = Counter()
    problem_passes = Counter()
    for sample in samples:
        for t in sample["test_details"]["passing_tests"]:
            problem_appearances[t["test_id"]] += 1
            problem_passes[t["test_id"]] += 1
        for t in sample["test_details"]["failing_tests"]:
            problem_appearances[t["test_id"]] += 1

    total_problems = len(problem_appearances)

    pass_k_values = {}
    for k in [1, 3, 5]:
        if k > n:
            pass_k_values[k] = 0.0
            continue
        weighted_sum = sum(
            pass_at_k(n, problem_passes[tid], k) for tid in problem_appearances
        )
        pass_k_values[k] = weighted_sum / total_problems * 100

    distribution = Counter()
    for tid in problem_appearances:
        distribution[problem_passes[tid]] += 1

    result = {
        "model": model,
        "dataset": dataset,
        "n_samples": n,
        "total_problems": total_problems,
        "pass_at_k": {f"pass@{k}": round(v, 2) for k, v in pass_k_values.items()},
        "pass_count_distribution": {
            f"{c}/5": count for c, count in sorted(distribution.items())
        },
    }

    return result


def print_results(result: Dict):
    print(f"Model: {result['model']}")
    print(f"Dataset: {result['dataset']}")
    print(f"Problems: {result['total_problems']}, Samples: {result['n_samples']}")
    print()
    print(f"  pass@1 = {result['pass_at_k']['pass@1']:.2f}%")
    if "pass@3" in result["pass_at_k"]:
        print(f"  pass@3 = {result['pass_at_k']['pass@3']:.2f}%")
    if "pass@5" in result["pass_at_k"]:
        print(f"  pass@5 = {result['pass_at_k']['pass@5']:.2f}%")
    print()
    print("  Pass count distribution:")
    for bucket, count in result["pass_count_distribution"].items():
        print(f"    {bucket}: {count} problems")


def main():
    parser = argparse.ArgumentParser(
        description="Compute pass@k from CVDP composite_report.json"
    )
    parser.add_argument(
        "work_dirs", nargs="+", help="Work directories containing composite_report.json"
    )
    parser.add_argument("--json", dest="json_output", help="Save results to JSON file")
    args = parser.parse_args()

    all_results = {}
    for work_dir in args.work_dirs:
        composite_path = Path(work_dir) / "composite_report.json"
        if not composite_path.exists():
            print(f"ERROR: {composite_path} not found", file=sys.stderr)
            sys.exit(1)
        result = compute_pass_at_k_from_composite(str(composite_path))
        label = Path(work_dir).name
        all_results[label] = result
        print(f"=== {label} ===")
        print_results(result)
        print()

    if args.json_output:
        with open(args.json_output, "w") as f:
            json.dump(all_results, f, indent=2)
        print(f"Results saved to {args.json_output}")


if __name__ == "__main__":
    main()
